#pragma once

#define USB_POLLING_INTERVAL_MS 1
#define DEBOUNCE 35
#undef PERMISSIVE_HOLD
#define PERMISSIVE_HOLD
#define PERMISSIVE_HOLD_PER_KEY
#undef QUICK_TAP_TERM
#define QUICK_TAP_TERM 90
#define QUICK_TAP_TERM_PER_KEY
#undef TAPPING_TERM
#define TAPPING_TERM 185
#define TAPPING_TERM_PER_KEY
#define ACHORDION_STREAK

#define OLED_TIMEOUT 30000
#define OLED_UPDATE_INTERVAL 100
#define SPLIT_LED_STATE_ENABLE

#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 9
#define MOUSEKEY_TIME_TO_MAX 64
#define MOUSEKEY_MAX_SPEED 2
#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_WHEEL_INTERVAL 150
#define MOUSEKEY_WHEEL_TIME_TO_MAX 70
#define MOUSEKEY_WHEEL_MAX_SPEED 15

#define WPM_ALLOW_COUNT_REGRESSION
#define WPM_SAMPLE_SECONDS 5
#define WPM_SAMPLE_PERIODS 25
#undef WPM_LAUNCH_CONTROL

